/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../src/components/Account.vue')['default']
    Chat: typeof import('./../src/components/Chat.vue')['default']
    Client: typeof import('./../src/components/Danmu/Client.vue')['default']
    Control: typeof import('./../src/components/Control.vue')['default']
    copy: typeof import('./../src/components/Danmu/Host copy.vue')['default']
    Danmu: typeof import('./../src/components/Danmu.vue')['default']
    DanmuDrawer: typeof import('./../src/components/Drawer/Danmu-Drawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Host: typeof import('./../src/components/Danmu/Host.vue')['default']
    Medal: typeof import('./../src/components/Medal.vue')['default']
    MusicDrawer: typeof import('./../src/components/Drawer/Music-Drawer.vue')['default']
    MusicList: typeof import('./../src/components/Music-List.vue')['default']
    QRCode: typeof import('./../src/components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
