/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./../components/Account.vue')['default']
    Background: typeof import('./../components/Background.vue')['default']
    BackgroundRender: typeof import('./../components/BackgroundRender.vue')['default']
    Chat: typeof import('./../components/Chat.vue')['default']
    Client: typeof import('./../components/Danmu/Client.vue')['default']
    Control: typeof import('./../components/Control.vue')['default']
    DanmuDrawer: typeof import('./../components/Drawer/Danmu-Drawer.vue')['default']
    DynamicBackground: typeof import('./../components/Dynamic-Background.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Host: typeof import('./../components/Danmu/Host.vue')['default']
    HostItem: typeof import('./../components/Danmu/HostItem.vue')['default']
    Medal: typeof import('./../components/Medal.vue')['default']
    MusicDrawer: typeof import('./../components/Drawer/Music-Drawer.vue')['default']
    MusicList: typeof import('./../components/Music-List.vue')['default']
    QRCode: typeof import('./../components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleA: typeof import('./../components/Danmu/SampleA.vue')['default']
    SampleB: typeof import('./../components/Danmu/SampleB.vue')['default']
  }
}
